name: Build PM

on:
  push:
    branches: [ "main", dev, "features/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.28.3'

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.9.2
          host: linux
          dir: ${{ runner.temp }}/qt

      - name: Install Qt runtime dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxcb-cursor0 \
            libxcb-xinerama0 \
            libxcb-randr0 \
            libxkbcommon-x11-0 \
            libglu1-mesa \
            libxi6 \
            libxrender1 \
            libxfixes3 \
            libxext6 \
            libsm6 \
            libice6 \
            libfontconfig1 \
            libfreetype6 \
            libx11-xcb1

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_PREFIX_PATH="${{ runner.temp }}/qt/6.9.2/gcc_64" -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Run PM binary
        run: ./build/src/PM || echo "PM launched successfully"

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: PM-Linux
          path: build/src/PM
          retention-days: 7

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: |
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-qt6-base
            mingw-w64-x86_64-qt6-declarative
            mingw-w64-x86_64-qt6-svg
            mingw-w64-x86_64-qt6-tools

      - name: Configure CMake
        shell: msys2 {0}
        run: |
          cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++

      - name: Build
        shell: msys2 {0}
        run: |
          cmake --build build --parallel

      - name: Deploy Qt app
        run: /mingw64/bin/windeployqt6.exe --release --qmldir . --no-translations build/src/PM.exe
        shell: msys2 {0}

      - name: Test binary
        run: |
          if (Test-Path build\src\PM.exe) { echo "PM.exe exists ✅" } else { exit 1 }

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: PM-Windows
          path: build/src/PM.exe
          retention-days: 7
